### ISSUE TITLE
Instalátor nevyhledává PTU

### ISSUE THREAD

**Issue by SonycCZE** [JarredSC/Star-Citizen-CZ-lokalizace#1]
Zdravím, vedle složky LIVE mám i složku PTU, instalátor ji vůbec nenajde a umožní instalaci pouze pro LIVE.
![Snímek obrazovky 2024-10-15 231546](https://github.com/user-attachments/assets/4d712d2a-c258-47fe-adbb-2ed2f9495a3a)
![Snímek obrazovky 2024-10-15 231456](https://github.com/user-attachments/assets/35b8bbff-d818-4096-802e-99b78bb56449)

**Comment by KissmanCZ** [comment]
Ahoj, toto by melo byt jiz vyreseno v aktualni verzi (0.4) instalatoru. Dej prosim vedet, jestli je vse OK. Diky. Btw. zrovna jsem vcera koukal na mapu, ze ses tady nekde pobliz zapadu?

**Comment by KissmanCZ** [comment]
Prepracovane hledani a instalace do PTU, fixnute od verze 0.4.
